name: Makepkg Build and Check
author: Eric Langlois
description: Build and check a PKGBUILD package
branding:
  color: blue
  icon: chevron-up
inputs:
  pkgdir:
    description: "Relative path to directory containing the PKGBUILD file."
    required: false
    default: "."
  cflags:
    description: "Append to CFLAGS"
    required: false
    default: ""
  cxxflags:
    description: "Append to CXXFLAGS"
    required: false
    default: ""
  ldflags:
    description: "Append to LDFLAGS"
    required: false
    default: ""
  rustcflags:
    description: "Append to LDFLAGS"
    required: false
    default: ""
  clanged: 
    description: "Use LLVM Toolchain to Compile"
    required: false
    default: "N"
  officialRepo:
    description: "Use Arch Repository LLVM Toolchain to Compile"
    required: false
    default: "N"
  bootstrap:
    description: "Use LLVM Bootstrap for build"
    required: false
    default: "N"
  clangedPFlags:
    description: "Use LLVM Toolchain Specific Flags to Compile"
    required: false
    default: "N"
  clangedPolly:
    description: "Use Polly - Polyhedral optimizations (Clang Only)"
    required: false
    default: "N"
  gccPFlags:
    description: "GCC Performance focused flags"
    required: false
    default: "N"
  namcapDisable:
    description: "Disable namcap checks if nonempty."
    required: false
    default: ""
  namcapRules:
    description: "A comma-separated list of rules for namcap to run."
    required: false
    default: ""
  namcapExcludeRules:
    description: "A comma-separated list of rules for namcap not to run."
    required: false
    default: ""
  makepkgArgs:
    description: "Additional arguments to pass to makepkg."
    required: false
    default: ""
  gpg:
    description: "Add GPG key"
    required: false
    default: ""
outputs:
  pkgfile0:
    description: "Filename of the first generated package archive. Usually only one."
  pkgfile1:
    description: "Filename of the 2nd generated package archive, etc."

runs:
  using: 'docker'
  image: 'Dockerfile'
