export CC="/usr/bin/gcc"
export CXX="/usr/bin/g++"
export CC_LD="/usr/bin/ld.mold"
export CXX_LD="/usr/bin/ld.mold"
export LD="/usr/bin/ld.mold"
export AR="/usr/bin/ar"
export NM="/usr/bin/nm"
export STRIP="/usr/bin/strip"
export OBJCOPY="/usr/bin/objcopy"
export OBJDUMP="/usr/bin/objdump"
export READELF="/usr/bin/readelf"
export RANLIB="/usr/bin/ranlib"
export HOSTCC="/usr/bin/gcc"
export HOSTCXX="/usr/bin/g++"
export HOSTAR="/usr/bin/ar"
export HOSTLD="/usr/bin/ld.mold"
export PROFILE=release

#-- Compiler and Linker Flags
_isl="-ftree-loop-linear -floop-strip-mine -floop-block"
_tree="-ftree-ter -ftree-lrs -ftree-loop-vectorize -ftree-loop-ivcanon"
_smal="-fsched-pressure -fira-hoist-pressure -fira-loop-pressure -fmodulo-sched -fmodulo-sched-allow-regmoves -fipa-icf"
_virtual="-fdevirtualize -fdevirtualize-at-ltrans -fdevirtualize-speculatively"
_sched="-fselective-scheduling2 -fpeephole2 -fsched-spec -fsel-sched-pipelining -fsel-sched-pipelining-outer-loops -ftree-loop-im -freorder-functions -fschedule-insns -fsched2-use-superblocks"
_limit="-fipa-strict-aliasing -flimit-function-alignment"
_loop="-funswitch-loops -fmove-loop-stores -ftree-partial-pre -fpeel-loops -ftree-loop-if-convert -freschedule-modulo-scheduled-loops -floop-unroll-and-jam -fpredictive-commoning -fgcse-lm -fgcse-sm -fivopts -flive-range-shrinkage -ftree-loop-ivcanon -funswitch-loops -ftree-loop-im -floop-interchange -floop-nest-optimize -ftree-loop-distribution"
_flags="-fvect-cost-model=cheap -fsplit-paths -fstdarg-opt -fuse-linker-plugin -ftree-vectorize -fdata-sections -ffunction-sections -mfpmath=sse -fgraphite -fgraphite-identity -fgcse-after-reload"
_cxx_flags="-fallocation-dce"
_pointer_analysis="-fipa-pta"

_cc="-march=x86-64-v3 -O2 -pipe -Wformat -Werror=format-security -fstack-clash-protection -fno-plt -fomit-frame-pointer -fcf-protection $_limit $_smal $_isl $_loop $_flags $_pointer_analysis"
_cxx="$_cc $_cxx_flags $_virtual"
_linker="-fuse-ld=mold -Wl,-O4 -Wl,--gc-sections -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--icf=safe -Wl,--threads"