export CC="/usr/bin/clang -fpass-plugin=LLVMPolly.so -mllvm -polly"
export CXX="/usr/bin/clang++ -fpass-plugin=LLVMPolly.so -mllvm -polly"
export CC_LD="/usr/bin/ld.lld --load-pass-plugin=LLVMPolly.so -mllvm -polly"
export CXX_LD="/usr/bin/ld.lld --load-pass-plugin=LLVMPolly.so -mllvm -polly"
export LD="/usr/bin/ld.lld --load-pass-plugin=LLVMPolly.so -mllvm -polly"
export AR="/usr/bin/llvm-ar"
export NM="/usr/bin/llvm-nm"
export STRIP="/usr/bin/llvm-strip"
export OBJCOPY="/usr/bin/llvm-objcopy"
export OBJDUMP="/usr/bin/llvm-objdump"
export READELF="/usr/bin/llvm-readelf"
export RANLIB="/usr/bin/llvm-ranlib"
export HOSTCC="/usr/bin/clang -fpass-plugin=LLVMPolly.so -mllvm -polly"
export HOSTCXX="/usr/bin/clang++ -fpass-plugin=LLVMPolly.so -mllvm -polly"
export HOSTAR="/usr/bin/llvm-ar"
export HOSTLD="/usr/bin/ld.lld --load-pass-plugin=LLVMPolly.so -mllvm -polly"
export QMAKESPEC=linux-clang
export PROFILE=release