_default="-Qunused-arguments \
    -ffunction-sections \
    -fdata-sections \
    -fno-plt \
    -fcolor-diagnostics \
    -pipe \
    -fstack-protector \
    -fstack-clash-protection \
    -Wformat \
    -Werror=format-security"

_extra_flags="$_extra_custom_flags"
_compiler="$_default -O3 $_extra_flags $_llvm $_polly $_verify -fuse-ld=lld"