_default="-Qunused-arguments -ffunction-sections -fdata-sections -fno-plt -fomit-frame-pointer -fdiagnostics-color=always -pipe -fstack-protector -fstack-clash-protection"
_plugin="$_custom_plugin"
_compiler="$_default -O3 -march=x86-64-v3 -fvectorize $_plugin $_flags $_llvm $_cse $_opt $_polly -fuse-ld=lld"