_default="-Qunused-arguments -ffunction-sections -fdata-sections -fno-plt -fomit-frame-pointer -fcolor-diagnostics -pipe -fstack-protector -fstack-clash-protection -Wformat -Werror=format-security"
_plugin="$_custom_plugin"
_compiler="$_default -O3 $_plugin $_flags $_llvm $_cse $_opt $_polly -fuse-ld=lld"