_vecmem="-mllvm --enable-interleaved-mem-accesses \
  -mllvm --enable-masked-interleaved-mem-accesses \
  -mllvm --lower-interleaved-accesses \
  -mllvm --dse-optimize-memoryssa \
  -mllvm --enable-mem-access-versioning \
  -mllvm --vectorize-loops \
  -mllvm --vectorize-slp \
  -mllvm --slp-vectorize-hor \
  -mllvm --slp-vectorize-hor-store \
  -mllvm --enable-early-exit-vectorization \
  -mllvm --enable-epilogue-vectorization"

_loops="-mllvm --enable-unroll-and-jam \
  -mllvm --enable-loop-flatten \
  -mllvm --interleave-loops \
  -mllvm --enable-split-loopiv-heuristic  \
  -mllvm --enable-loop-versioning-licm \
  -mllvm --scalar-evolution-use-expensive-range-sharpening \
  -mllvm --extra-vectorizer-passes \
  -mllvm --loop-fusion-peel-max-count=4 \
  -mllvm --loop-idiom-vectorize-style=masked \
  -mllvm --loop-version-annotate-no-alias \
  -mllvm --lv-strided-pointer-ivs \
  -mllvm --enable-loopinterchange \
  -mllvm --licm-control-flow-hoisting"

_sched="-mllvm --misched-cyclicpath \
  -mllvm --enable-misched \
  -mllvm --enable-post-misched \
  -mllvm --schedmodel \
  -mllvm --scheditins \
  -mllvm --isel-rebalance-addr"

_math="-mllvm --costmodel-reduxcost \
  -mllvm --mul-constant-optimization \
  -mllvm --rebalance-only-opt \
  -mllvm --reassociate-geps-verify-no-dead-code \
  -mllvm --reassociate-use-cse-local"

_global="-mllvm --enable-global-analyses \
  -mllvm --enable-cse-in-irtranslator \
  -mllvm --ir-outliner"

_branch="-mllvm --branch-fold-placement \
  -mllvm --enable-if-conversion \
  -mllvm --enable-chr \
  -mllvm --enable-cond-stores-vec"

_reg="-mllvm --optimize-regalloc \
  -mllvm --inline-enable-cost-benefit-analysis \
  -mllvm --enable-lsr-phielim \
  -mllvm --enable-ipra \
  -mllvm --hoist-common-insts \
  -mllvm --hoist-const-loads \
  -mllvm --enable-local-reassign"

# SLOW
#_verify="-mllvm --verify-machineinstrs -mllvm --verify-coalescing -mllvm --verify-regalloc -mllvm --scev-verify-ir"
_llvm="-fslp-vectorize -fvectorize $_vecmem $_loops $_sched $_math $_global $_branch $_reg $_verify"