_ldrust="-C link-arg=-fuse-ld=lld -C link-arg=-O4 -C link-arg=-z -C link-arg=now -C link-arg=-z -C link-arg=relro -C link-arg=--as-needed -C link-arg=--gc-sections -C link-arg=--icf=safe -C link-arg=--hash-style=gnu"

_vecmem="-Cllvm-args=enable-interleaved-mem-accesses \
         -Cllvm-args=enable-masked-interleaved-mem-accesses \
         -Cllvm-args=lower-interleaved-accesses \
         -Cllvm-args=dse-optimize-memoryssa \
         -Cllvm-args=enable-mem-access-versioning \
         -Cllvm-args=enable-memprof-context-disambiguation \
         -Cllvm-args=vectorize-loops \
         -Cllvm-args=vectorize-slp \
         -Cllvm-args=slp-vectorize-hor \
         -Cllvm-args=slp-vectorize-hor-store \
         -Cllvm-args=enable-early-exit-vectorization \
         -Cllvm-args=enable-epilogue-vectorization"


_loops="-Cllvm-args=enable-loopinterchange \
       -Cllvm-args=enable-loop-distribute \
       -Cllvm-args=enable-unroll-and-jam \
       -Cllvm-args=interleave-loops \
       -Cllvm-args=loop-rotate-multi \
       -Cllvm-args=enable-loop-flatten \
       -Cllvm-args=enable-split-loopiv-heuristic \
       -Cllvm-args=enable-loop-versioning-licm \
       -Cllvm-args=scalar-evolution-use-expensive-range-sharpening \
       -Cllvm-args=extra-vectorizer-passes \
       -Cllvm-args=loop-distribute-verify \
       -Cllvm-args=loop-fusion-peel-max-count=4 \
       -Cllvm-args=loop-idiom-vectorize-style=masked \
       -Cllvm-args=loop-version-annotate-no-alias \
       -Cllvm-args=enable-loop-header-duplication \
       -Cllvm-args=lv-strided-pointer-ivs \
       -Cllvm-args=indvars-predicate-loops"

_branch="-Cllvm-args=branch-fold-placement \
        -Cllvm-args=enable-if-conversion \
        -Cllvm-args=enable-chr \
        -Cllvm-args=enable-cond-stores-vec"

_reg="-Cllvm-args=optimize-regalloc \
     -Cllvm-args=inline-enable-cost-benefit-analysis \
     -Cllvm-args=enable-lsr-phielim \
     -Cllvm-args=enable-ipra \
     -Cllvm-args=aggressive-ext-opt \
     -Cllvm-args=hoist-common-insts \
     -Cllvm-args=hoist-const-loads \
     -Cllvm-args=enable-local-reassign"

# SLOW
#_verify="-mllvm --verify-machineinstrs -mllvm --verify-coalescing -mllvm --verify-regalloc -mllvm --scev-verify-ir"
# _rllvm="$_vecmem $_loops $_branch $_reg"